### ISSUE TITLE
DataFrame.ToCSV throwing InvalidCastException

### ISSUE THREAD

**Issue by raymond130** [bhrnjica/daany#10]
Hi there,

when trying to save the dataframes in the "Predictive Maintenance in .NET" notebook, DataFrame.ToCsv throws an InvalidCastException from within the function; code is as follows:

`//constructing the label column which indicate if the current machine will 
//fail in the next `predTime` (24 hours as default) due to failur certain component.
//create final data frame from from feature df
var finalDf = new DataFrame(features_final);

//group failures by machineID and datetime 
string[] cols = new string[] {  "machineID" , "datetime"};
var failDfgrp = failures.GroupBy(cols);

//Add failure column to  finalDF
finalDf.AddCalculatedColumn("failure", (object[]row, int i) => "none");
finalDf.RowCount();

DataFrame.ToCsv("../df1roll121212.txt", finalDf);
finalDf=DataFrame.FromCsv(@"../df1roll121212.txt");
`

And the stack trace:

`Error: System.InvalidCastException: Invalid cast from 'Double' to 'DateTime'.
at System.Double.System.IConvertible.ToDateTime(IFormatProvider provider)
at Daany.DataFrame.ToCsv(String filePath, DataFrame dataFrame, Char delimiter, String dateFormat, Boolean writHeader)
at Submission#70.<<Initialize>>d__0.MoveNext()
--- End of stack trace from previous location ---
at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.RunSubmissionsAsync[TResult](ImmutableArray`1 precedingExecutors, Func`2 currentExecutor, StrongBox`1 exceptionHolderOpt, Func`2 catchExceptionOpt, CancellationToken cancellationToken)`

**Comment by bhrnjica** [comment]
If it throws the Exception at this line: `finalDf=DataFrame.FromCsv(@"../df1roll121212.txt");` try to see if all columns are valid. Moreover if there is a dateTime column you have to specified datetime format. 
Please take a look at this notebook if you haven't already.

https://github.com/bhrnjica/notebooks/blob/master/notebooks/PrM/Predictive_maintenance_100_cnc_machines.ipynb

**Comment by raymond130** [comment]
Hey Bahrudin, I believe this might be related to another issue I'm having - in step 72 and 73 of the notebook in the link you provided:

`finalDf.AddCalculatedColumn("failure", (object[]row, int i) => "none");
finalDf.RowCount();`


After this step runs, the next step is 
`var featureDfGrouped1 = finalDf["datetime","machineID", "failure"];`


and unfortunately, every time this runs, I reach an indexoutofrange exception, originating from the this(string[]).get() method from the Dataframe class. I've investigated a little further and it looks like what's happening is that when the calculated column is added, the _columns  property contains the correct number and kind of columns (30), but the _colstype property doesn't seem to have the proper type (string) added, meaning it only has 29 entries. 

So when the get() function is called, it looks for the coltype and can't find it (an index out of range is returned) because it wants the 30th entry in _colstype, which only has 29 entries.


Right now I'm maybe trying to step into the code and figure out what goes wrong, but I'm not sure - given that the other calculated column functions work properly - I'm not sure what could be wrong. I've even tried using the different implementations of the addcalculatedcolumns() functions to see if it's a one off bug, but it looks to be deeper in the code.

I hope this helps, any assistance would be welcome
Thanks,
Brandon

**Comment by bhrnjica** [comment]
Hi Brandon,

Can you provide the code that reproduce the bug? I would like to help to fix it.

Bahrudin

**Comment by raymond130** [comment]
Hey Bahrudin,

If you don't mind, I'll include the visual studio solution files as well as the code - because the code references a few other classes I created to help encapsulate the feature engineering process you had in your article (I think if you compare side by side though mine isn't too different syntactically). Note for the solution, I had to remove the datafiles to make the size work with github's upload limits, but you can restore the functionality just by placing the five .csv files used in the program into the datafiles folder.

[Predictive Maintenance.zip](https://github.com/bhrnjica/daany/files/12457255/Predictive.Maintenance.zip)

the operational code is in the UnitTest class, as follows: 

`  public UnitTest()
        {
            //The first step goes through setting up the dataframe templates and importing data

            Formatter.Register<DataFrame>((df, writer) =>
            {
                var headers = new List<IHtmlContent>();
                headers.Add(th(i("index")));
                headers.AddRange(df.Columns.Select(c => (IHtmlContent)th(c)));
                //renders the rows
                var rows = new List<List<IHtmlContent>>();
                var take = 20;
                //
                for (var i = 0; i < Math.Min(take, df.RowCount()); i++)
                {
                    var cells = new List<IHtmlContent>();
                    cells.Add(td(df.Index[i]));
                    foreach (var obj in df[i])
                    {
                        cells.Add(td(obj));
                    }
                    rows.Add(cells);
                }
                var t = table(
                    thead(headers),
                    tbody(rows.Select(r => tr(r))));

                writer.Write(t);
            }, "text/html");

            //Load ALL 5 data frame files
            //DataFrame Cols: datetime,machineID,volt,rotate,pressure,vibration


            var telemetry = DataFrame.FromCsv(@"C:\Users\braymond\source\repos\predictive-maintenance\Predictive Maintenance\Data Preparation\DataFiles\PdM_telemetry.csv", dformat: "yyyy-mm-dd hh:mm:ss");
            var errors = DataFrame.FromCsv(@"C:\Users\braymond\source\repos\predictive-maintenance\Predictive Maintenance\Data Preparation\DataFiles\PdM_errors.csv", dformat: "yyyy-mm-dd hh:mm:ss");
            var maint = DataFrame.FromCsv(@"C:\Users\braymond\source\repos\predictive-maintenance\Predictive Maintenance\Data Preparation\DataFiles\PdM_maint.csv", dformat: "yyyy-mm-dd hh:mm:ss");
            var failures = DataFrame.FromCsv(@"C:\Users\braymond\source\repos\predictive-maintenance\Predictive Maintenance\Data Preparation\DataFiles\PdM_failures.csv", dformat: "yyyy-mm-dd hh:mm:ss");
            var machines = DataFrame.FromCsv(@"C:\Users\braymond\source\repos\predictive-maintenance\Predictive Maintenance\Data Preparation\DataFiles\PdM_machines.csv", dformat: "yyyy-mm-dd hh:mm:ss");

            //create a new dataprep instance to use the helper functions
            DataPrep prep = new DataPrep();

            //prepare rolling aggregation for each column for last values
            var agg_current = new Dictionary<string, Aggregation>()
             {
                { "datetime", Aggregation.Last }, { "volt", Aggregation.Last },
                { "rotate", Aggregation.Last },
                { "pressure", Aggregation.Last },{ "vibration", Aggregation.Last }
              };
            //prepare rolling aggregation for each column for average values
            var agg_mean = new Dictionary<string, Aggregation>()
             {
                { "datetime", Aggregation.Last }, { "volt", Aggregation.Avg },
                { "rotate", Aggregation.Avg },
                { "pressure", Aggregation.Avg },{ "vibration", Aggregation.Avg }
              };
            //prepare rolling aggregation for each column for std values
            var agg_std = new Dictionary<string, Aggregation>()
            {
               { "datetime", Aggregation.Last }, { "volt", Aggregation.Std },
               { "rotate", Aggregation.Std },
               { "pressure", Aggregation.Std },{ "vibration", Aggregation.Std }
            };

            //Creating rolling aggregations to use as summarizations of telemetry data over time

            var groupedTelemetry = telemetry.GroupBy("machineID");

            var _3AvgValue = prep.createRolling(groupedTelemetry, agg_mean, 3, new (string, string)[6]{ ("machineID", null),
                         ("datetime", null), ("volt", "voltmean_3hrs"),
                         ("rotate", "rotatemean_3hrs"),
                         ("pressure", "pressuremean_3hrs"),
                         ("vibration", "vibrationmean_3hrs")});

            var _3StdValue = prep.createRolling(groupedTelemetry, agg_std, 3, new (string, string)[6]{("machineID", null), ("datetime", null),
                 ("volt", "voltsd_3hrs"), ("rotate", "rotatesd_3hrs"),
                         ("pressure", "pressuresd_3hrs"), ("vibration", "vibrationsd_3hrs") });

            var _24AvgValue = prep.createRolling(groupedTelemetry, agg_mean, 24, new (string, string)[6] {("machineID", null), ("datetime", null),
                        ("volt", "voltmean_24hrs"), ("rotate", "rotatemean_24hrs"),
                        ("pressure", "pressuremean_24hrs"),
                        ("vibration", "vibrationmean_24hrs")});

            var _24StdValue = prep.createRolling(groupedTelemetry, agg_std, 24, new (string, string)[]{("machineID", null), ("datetime", null),
                        ("volt", "voltsd_24hrs"), ("rotate", "rotatesd_24hrs"),
                        ("pressure", "pressuresd_24hrs"),
                        ("vibration", "vibrationsd_24hrs") });

            DataFrame _1CurrentValue = prep.createRolling(groupedTelemetry, agg_current, 3, new (string, string)[] {("machineID", null), ("datetime", null),
                            ("volt", null), ("rotate", null),
                            ("pressure", null), ("vibration", null)});

            //Merging all these columns together to create a combined telemetry dashboard

            var mergeCols = new string[] { "machineID", "datetime" };

            var df1 = _1CurrentValue.Merge
                      (_3AvgValue, mergeCols, mergeCols, JoinType.Left, suffix: "df1");

            var df2 = df1.Merge(_24AvgValue, mergeCols, mergeCols, JoinType.Left, suffix: "df2");

            var df3 = df2.Merge(_3StdValue, mergeCols, mergeCols, JoinType.Left, suffix: "df3");

            var df4 = df3.Merge(_24StdValue, mergeCols, mergeCols, JoinType.Left, suffix: "df4");

            var telDF = df4["machineID", "datetime", "volt", "rotate", "pressure", "vibration",
                 "voltmean_3hrs", "rotatemean_3hrs", "pressuremean_3hrs", "vibrationmean_3hrs",
                 "voltmean_24hrs", "rotatemean_24hrs", "pressuremean_24hrs", "vibrationmean_24hrs",
                 "voltsd_3hrs", "rotatesd_3hrs", "pressuresd_3hrs", "vibrationsd_3hrs",
                 "voltsd_24hrs", "rotatesd_24hrs", "pressuresd_24hrs", "vibrationsd_24hrs"];

            var telemetry_final = telDF.DropNA();

            //One-hot (categorial to boolean) encoding of error columns, aggregating errors  then joining to main dataset

            var mlContext = new MLContext(seed: 2019);
            var encodedErr = errors.TransformColumn("errorID", ColumnTransformer.OneHot);
            var errors_aggs = new Dictionary<string, Aggregation>();
            errors_aggs.Add("error1", Aggregation.Sum);
            errors_aggs.Add("error2", Aggregation.Sum);
            errors_aggs.Add("error3", Aggregation.Sum);
            errors_aggs.Add("error4", Aggregation.Sum);
            errors_aggs.Add("error5", Aggregation.Sum);

            encodedErr.df = encodedErr.df.GroupBy(new string[]
              { "machineID", "datetime" }).Aggregate(errors_aggs);

            encodedErr.df = encodedErr.df.Create(("machineID", null), ("datetime", null),
                        ("error1", "error1sum"), ("error2", "error2sum"),
                        ("error3", "error3sum"), ("error4", "error4sum"),
                        ("error5", "error5sum"));

            var er = telemetry.Merge(encodedErr.df, mergeCols, mergeCols, JoinType.Left, suffix: "error");

            //creating separate error columns and aggregating into them

            er = er["machineID", "datetime", "error1sum", "error2sum", "error3sum", "error4sum", "error5sum"];
            er.FillNA(0);

            var errors_aggs1 = new Dictionary<string, Aggregation>()
            {
              { "datetime", Aggregation.Last },{ "error1sum", Aggregation.Sum },
              { "error2sum", Aggregation.Sum },
              { "error3sum", Aggregation.Sum },{ "error4sum", Aggregation.Sum },
              { "error5sum", Aggregation.Sum }
            };

            //24 hour rolling aggregates of errors

            var eDF = er.GroupBy(new string[] { "machineID" }).Rolling(24, 3, errors_aggs1);

            var newdf = eDF.DropNA();

            var errors_final = newdf.Create(("machineID", null), ("datetime", null),
                        ("error1sum", "error1count"), ("error2sum", "error2count"),
                        ("error3sum", "error3count"),
                        ("error4sum", "error4count"), ("error5sum", "error5count"));


            //boolean encoding of the replacement components column, telling us that a component has been replaced

            var encMaint = maint.TransformColumn("comp", ColumnTransformer.OneHot).df;

            DataFrame dfComp1 = encMaint.Filter("comp1", 1, FilterOperator.Equal)["machineID", "datetime"];
            DataFrame dfComp2 = encMaint.Filter("comp2", 1, FilterOperator.Equal)["machineID", "datetime"]; 
            DataFrame dfComp3 = encMaint.Filter("comp3", 1, FilterOperator.Equal)["machineID", "datetime"]; 
            DataFrame dfComp4 = encMaint.Filter("comp4", 1, FilterOperator.Equal)["machineID", "datetime"];

            var compData = telemetry_final.Create(("machineID", null), ("datetime", null));

            var newCols = new string[] { "sincelastcomp1", "sincelastcomp2", "sincelastcomp3", "sincelastcomp4" };
            var calcValues = new object[4];

            compData.AddCalculatedColumns(newCols, (row, i) =>
            {
                var machineId = Convert.ToInt32(row["machineID"]);
                var date = Convert.ToDateTime(row["datetime"]);

                var maxDate1 = dfComp1.Filter("machineID", machineId, FilterOperator.Equal)["datetime"]
                    .Where(x => (DateTime)x <= date).Select(x => (DateTime)x).Max();
                var maxDate2 = dfComp2.Filter("machineID", machineId, FilterOperator.Equal)["datetime"]
                    .Where(x => (DateTime)x <= date).Select(x => (DateTime)x).Max();
                var maxDate3 = dfComp3.Filter("machineID", machineId, FilterOperator.Equal)["datetime"]
                    .Where(x => (DateTime)x <= date).Select(x => (DateTime)x).Max();
                var maxDate4 = dfComp4.Filter("machineID", machineId, FilterOperator.Equal)["datetime"]
                    .Where(x => (DateTime)x <= date).Select(x => (DateTime)x).Max();

                //perform calculation
                calcValues[0] = (date - maxDate1).TotalDays;
                calcValues[1] = (date - maxDate2).TotalDays;
                calcValues[2] = (date - maxDate3).TotalDays;
                calcValues[3] = (date - maxDate4).TotalDays;
                return calcValues;
            });

            var maintenance_final = compData;

            var merge2Cols = new string[] { "machineID" };
            var fdf1 = telemetry_final.Merge(errors_final, mergeCols, mergeCols, JoinType.Left, suffix: "er");
            var fdf2 = fdf1.Merge(maintenance_final, mergeCols, mergeCols, JoinType.Left, suffix: "mn");
            var features_final = fdf2.Merge(machines, merge2Cols, merge2Cols, JoinType.Left, suffix: "ma");


            //Generating the final features dataframe that we can load into our ML model and process

            features_final = features_final["datetime", "machineID",
            "voltmean_3hrs", "rotatemean_3hrs", "pressuremean_3hrs", "vibrationmean_3hrs",
            "voltsd_3hrs", "rotatesd_3hrs", "pressuresd_3hrs", "vibrationsd_3hrs",
            "voltmean_24hrs", "rotatemean_24hrs", "pressuremean_24hrs", "vibrationmean_24hrs",
            "voltsd_24hrs", "rotatesd_24hrs", "pressuresd_24hrs", "vibrationsd_24hrs",
            "error1count", "error2count", "error3count", "error4count", "error5count",
            "sincelastcomp1", "sincelastcomp2", "sincelastcomp3", "sincelastcomp4",
            "model", "age"];

           // DataFrame.ToCsv("../final_features.csv", features_final, dateFormat: "D");

            finalDFPrepped = features_final;

            //constructing the label column which indicate if the current machine will 
            //fail in the next `predTime` (24 hours as default) due to failure of a certain component.
            //create final data frame from feature df
            var finalDf = new DataFrame(features_final);

            //group failures by machineID and datetime 
            string[] cols = new string[] { "machineID", "datetime" };
            var failDfgrp = failures.GroupBy(cols);

            //Add failure column to  finalDF
            var rV = new object[] { "none" };
            finalDf.AddCalculatedColumn( "failure", (object[] row, int i) => "none");
            //finalDf.AddCalculatedColumn("failure", (object[] row, int i) => "none");
            //finalDf.RowCount();

            //create new data frame from featuresDF by grouping machineID and datatime
            var featureDf = finalDf["datetime", "machineID", "failure"];
                
            var featureDfGrouped = featureDf.GroupBy(cols);

            //now look for every failure and calculate if the machine will fail in the last 24 hours
            //in case two or more components were failed for the same machine add new row in df
            var failureDfExt = featureDfGrouped.Transform((xdf) =>
            {
                //extract the row from featureDfGrouped
                var xdfRow = xdf[0].ToList();
                var refDate = (DateTime)xdfRow[0];
                var machineID = (int)xdfRow[1];

                //now look if the failure contains the machineID
                if (failDfgrp.Group2.ContainsKey(machineID))
                {
                    //get the date and calculate total hours
                    var dff = failDfgrp.Group2[machineID];

                    foreach (var dfff in dff)
                    {
                        for (int i = 0; i < dfff.Value.RowCount(); i++)
                        {
                            //"datetime","machineID","failure"
                            var frow = dfff.Value[i].ToList();
                            var dft = (DateTime)frow[0];

                            //if total hours is less or equal than 24 hours set component 
                            //to the failure column
                            var totHours = (dft - refDate).TotalHours;
                            if (totHours <= 24 && totHours >= 0)
                            {
                                if (xdf.RowCount() > i)
                                    xdf["failure", i] = frow[2];
                                else//in case two components were failed for the same machine and 
                                    //at the same time, add new row with new component name
                                {
                                    var r = xdf[0].ToList();
                                    r[2] = frow[2];
                                    xdf.AddRow(r);
                                }
                            }
                        }
                    }
                }
                return xdf;
            });

            var final_dataframe = finalDf.Merge(failureDfExt, cols, cols, JoinType.Left, "fail");
            finalDFPrepped = final_dataframe;


            //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
            //Now entering the methods for doing machine learning/modelling and outputting the result, transformation
            //~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

            mlContext = new MLContext(seed: 88888);
            var strPath = "data/final_dataFrame.csv";
            var mlDF = DataFrame.FromCsv(strPath);
            //
            //split data frame on training and testing part
            //split at 2015-08-01 00:00:00, 
            //to train on the first 8 months and test on last 4 months
            var trainDF = mlDF.Filter("datetime", new DateTime(2015, 08, 1, 1, 0, 0),
                                       FilterOperator.LessOrEqual);
            var testDF = mlDF.Filter("datetime", new DateTime(2015, 08, 1, 1, 0, 0),
                                      FilterOperator.Greather);


            var modellingDummy = new Modelling();
            var prmainclass = new PrMaintenanceClass();

            var trainData = modellingDummy.loadFromDataFrame(mlContext, trainDF,prmainclass);
            var testData = modellingDummy.loadFromDataFrame(mlContext, testDF, prmainclass);

            string[] featurenames = new string[] {nameof(PrMaintenanceClass.voltmean_3hrs), nameof(PrMaintenanceClass.rotatemean_3hrs),
            nameof(PrMaintenanceClass.pressuremean_3hrs), nameof(PrMaintenanceClass.vibrationmean_3hrs),
            nameof(PrMaintenanceClass.voltstd_3hrs), nameof(PrMaintenanceClass.rotatestd_3hrs),
            nameof(PrMaintenanceClass.pressurestd_3hrs), nameof(PrMaintenanceClass.vibrationstd_3hrs),
            nameof(PrMaintenanceClass.voltmean_24hrs), nameof(PrMaintenanceClass.rotatemean_24hrs),
            nameof(PrMaintenanceClass.pressuremean_24hrs),
            nameof(PrMaintenanceClass.vibrationmean_24hrs),
            nameof(PrMaintenanceClass.voltstd_24hrs), nameof(PrMaintenanceClass.rotatestd_24hrs),
            nameof(PrMaintenanceClass.pressurestd_24hrs), nameof(PrMaintenanceClass.vibrationstd_24hrs),
            nameof(PrMaintenanceClass.error1count), nameof(PrMaintenanceClass.error2count),
            nameof(PrMaintenanceClass.error3count), nameof(PrMaintenanceClass.error4count),
            nameof(PrMaintenanceClass.error5count), nameof(PrMaintenanceClass.sincelastcomp1),
            nameof(PrMaintenanceClass.sincelastcomp2), nameof(PrMaintenanceClass.sincelastcomp3),
            nameof(PrMaintenanceClass.sincelastcomp4),
            nameof(PrMaintenanceClass.model), nameof(PrMaintenanceClass.age)};

            var transformationpipeline = modellingDummy.PrepareData(mlContext, nameof(prmainclass.failure),featurenames);

            var pp = transformationpipeline.Fit(trainData);
            var transformedData = pp.Transform(trainData);

            var model = modellingDummy.Train(mlContext, trainData);

            var predictions = model.Transform(trainData);
            var metricsTrain = mlContext.MulticlassClassification.Evaluate(predictions);

            //PrintMultiClassClassificationMetrics("TRAIN DataSet", metricsTrain);
            //ConsoleHelper.ConsoleWriteHeader("Train DataSet Confusion Matrix ");
            //ConsoleHelper.ConsolePrintConfusionMatrix(metricsTrain.ConfusionMatrix);
            
            //Writing output to a test file

            var currDate = DateTime.Now;
            var filePath = @"\DataFiles\Test" + currDate;

            File.WriteAllText(filePath, "~~~~~~~~~~ \n Metrics for TRAIN dataset \n~~~~~~~~~~");
            File.AppendAllText(filePath, metricsTrain.ToString());
            File.WriteAllText(filePath, "~~~~~~~~~~ \n Test Dataset confusion matrix \n~~~~~~~~~~");
            File.AppendAllText(filePath,metricsTrain.ConfusionMatrix.ToString());

            var testPrediction = model.Transform(testData);
            var metricsTest = mlContext.MulticlassClassification.Evaluate(testPrediction);

            File.WriteAllText(filePath, "~~~~~~~~~~ \n Metrics for TRAIN dataset \n~~~~~~~~~~");
            File.AppendAllText(filePath, metricsTest.ToString());
            File.WriteAllText(filePath, "~~~~~~~~~~ \n Test Dataset confusion matrix \n~~~~~~~~~~");
            File.AppendAllText(filePath, metricsTest.ConfusionMatrix.ToString());

`

Note that I think around line 280 is when the error happens, everything until then goes smoothly.

Thanks for any help! Let me know if i can help you at all or offer assistance

Thanks,
Brandon

**Comment by bhrnjica** [comment]
Hi Brandon,

thanx for the sample code.

Seems there is a bug in  `AddCalculatedColumn` you used, so just replace it with the following `finalDf.AddCalculatedColumn( "failure", (IDictionary<string, object> row, int i) => (object) "none");` at the line 270

And the rest of code should works.

**Comment by raymond130** [comment]
Hey Bahrudin, thank you it works!
