### ISSUE TITLE
Package Daany.DataFrame 1.2.0 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Package Daany.DataFrame 1.2.0 supports: net6.0 (.NETCoreApp,Version=v6.0)

### ISSUE THREAD

**Issue by praveenraghuvanshi1512** [bhrnjica/daany#6]
I am getting below error while installing the package in .Net interactive within Jupyter Notebook

**Package Daany.DataFrame 1.2.0 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Package Daany.DataFrame 1.2.0 supports: net6.0 (.NETCoreApp,Version=v6.0)**

I have uninstalled .Net 5.0 from my system and installed .Net 6.0 fresh, still getting this error.

![image](https://user-images.githubusercontent.com/39731863/152633650-742f130d-ce15-47eb-b3b9-11206eacc66d.png)

In control panel, there is only .Net 6.0
![image](https://user-images.githubusercontent.com/39731863/152633779-0c1d6289-c656-4330-93ed-90760f44ef54.png)

If you want, the notebook is available at https://github.com/praveenraghuvanshi/tech-sessions/blob/master/16062021-Global-AI-Community-2021/CricketAnalysis.ipynb

Let me know if you need more information.

**Comment by bhrnjica** [comment]
Hi, 

I tried your notebook within Visual Studio Code, where I have installed only C#, NET Interactive and NET SDK 6.01 components. I have successfully installed the package `Daany.DataFrame`.

![image](https://user-images.githubusercontent.com/1240016/152647514-6c2d4694-d343-43f4-a5bd-0d572ac56629.png)



I would suggest to delete all daany related packages from the `.nuget` folder, located at `c:\Users\YOUR_USERNAME\packages\.nuget` .

**Comment by praveenraghuvanshi1512** [comment]
Thanks for quick response!
I tried deleting packages from .nuget folder, still got the same error.
However, version 1.0.0 is installed properly. Not sure why latest version 1.2.0 is not working on my system
I have a workaround to work with as of now.

![image](https://user-images.githubusercontent.com/39731863/152653406-92623780-bc39-4362-84bd-e11eff92627a.png)

**Comment by bhrnjica** [comment]
Hi
 I just released the new NuGet package v1.3.0 for all packages by targeting multiple dotnet (`net6.0`;`net5.0`;`netcoreapp3.1`)
 
 Please try, now any dotnet core version 3.1+ should be supported by default.

I case you have a problem installing the version, please reopen this issue.
